# Form implementation generated from reading ui file 'profile.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Profile(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 581)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Vyhod = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Vyhod.setGeometry(QtCore.QRect(200, 510, 75, 23))
        self.Vyhod.setObjectName("Vyhod")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 81, 31))
        self.label.setObjectName("label")
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=self.centralwidget)
        self.calendarWidget.setGeometry(QtCore.QRect(80, 290, 312, 183))
        self.calendarWidget.setObjectName("calendarWidget")
        self.Name_profile = QtWidgets.QLabel(parent=self.centralwidget)
        self.Name_profile.setGeometry(QtCore.QRect(70, 60, 47, 13))
        self.Name_profile.setObjectName("Name_profile")
        self.Name_profile_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name_profile_2.setGeometry(QtCore.QRect(60, 90, 113, 20))
        self.Name_profile_2.setObjectName("Name_profile_2")
        self.Email_profile = QtWidgets.QLabel(parent=self.centralwidget)
        self.Email_profile.setGeometry(QtCore.QRect(60, 130, 47, 13))
        self.Email_profile.setObjectName("Email_profile")
        self.Email_profile_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Email_profile_2.setGeometry(QtCore.QRect(60, 170, 113, 20))
        self.Email_profile_2.setObjectName("Email_profile_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 461, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Vyhod.setText(_translate("MainWindow", "Выход"))
        self.label.setText(_translate("MainWindow", "Профиль"))
        self.Name_profile.setText(_translate("MainWindow", "Name"))
        self.Email_profile.setText(_translate("MainWindow", "Email"))
