# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Register(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(644, 413)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 20, 141, 21))
        self.label.setObjectName("label")
        self.Name_reg = QtWidgets.QLabel(parent=self.centralwidget)
        self.Name_reg.setGeometry(QtCore.QRect(70, 70, 71, 16))
        self.Name_reg.setObjectName("Name_reg")
        self.Name_vod_reg = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Name_vod_reg.setGeometry(QtCore.QRect(40, 100, 113, 20))
        self.Name_vod_reg.setObjectName("Name_vod_reg")
        self.Email_reg = QtWidgets.QLabel(parent=self.centralwidget)
        self.Email_reg.setGeometry(QtCore.QRect(70, 140, 71, 16))
        self.Email_reg.setObjectName("Email_reg")
        self.Email_vod_reg = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Email_vod_reg.setGeometry(QtCore.QRect(40, 180, 113, 20))
        self.Email_vod_reg.setObjectName("Email_vod_reg")
        self.Pass_reg = QtWidgets.QLabel(parent=self.centralwidget)
        self.Pass_reg.setGeometry(QtCore.QRect(60, 230, 71, 21))
        self.Pass_reg.setObjectName("Pass_reg")
        self.Pass_vod = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Pass_vod.setGeometry(QtCore.QRect(40, 260, 113, 20))
        self.Pass_vod.setObjectName("Pass_vod")
        self.Zaregistr = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Zaregistr.setGeometry(QtCore.QRect(124, 312, 161, 21))
        self.Zaregistr.setObjectName("Zaregistr")
        self.Vyhod = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Vyhod.setGeometry(QtCore.QRect(320, 312, 151, 21))
        self.Vyhod.setObjectName("Vyhod")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 644, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Регистрация"))
        self.Name_reg.setText(_translate("MainWindow", "Name"))
        self.Email_reg.setText(_translate("MainWindow", "Email"))
        self.Pass_reg.setText(_translate("MainWindow", "Password"))
        self.Zaregistr.setText(_translate("MainWindow", "Зарегистрироваться"))
        self.Vyhod.setText(_translate("MainWindow", "Выход"))
