# Form implementation generated from reading ui file 'vhod.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Vhod(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(645, 417)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 171, 21))
        self.label.setObjectName("label")
        self.Email = QtWidgets.QLabel(parent=self.centralwidget)
        self.Email.setGeometry(QtCore.QRect(40, 53, 121, 16))
        self.Email.setObjectName("Email")
        self.Email_Vod = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Email_Vod.setGeometry(QtCore.QRect(30, 89, 201, 21))
        self.Email_Vod.setObjectName("Email_Vod")
        self.Password = QtWidgets.QLabel(parent=self.centralwidget)
        self.Password.setGeometry(QtCore.QRect(40, 132, 91, 21))
        self.Password.setObjectName("Password")
        self.Pass_vod = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.Pass_vod.setGeometry(QtCore.QRect(30, 169, 171, 21))
        self.Pass_vod.setObjectName("Pass_vod")
        self.Vhod = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Vhod.setGeometry(QtCore.QRect(50, 242, 101, 31))
        self.Vhod.setObjectName("Vhod")
        self.Register = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Register.setGeometry(QtCore.QRect(230, 242, 91, 31))
        self.Register.setObjectName("Register")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 645, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Нчальная страница"))
        self.Email.setText(_translate("MainWindow", "Email"))
        self.Password.setText(_translate("MainWindow", "Password"))
        self.Vhod.setText(_translate("MainWindow", "Вход"))
        self.Register.setText(_translate("MainWindow", "Регистрация"))
